(function(){
var badge=document.getElementById("user-alarm-status");if(!badge)return;
function state(text,kind){badge.textContent=text;badge.className="user-alarm-status "+kind;}
function key(v){return String(v||"").trim().toLowerCase();}
function scopeSites(sites,u){if(key(u.role)==="aem")return sites;if(key(u.role)==="owner"&&u.ownerId)return sites.filter(s=>key(s.ownerId||s.owner)===key(u.ownerId));if(key(u.role)==="mgmt"&&u.mgmtCompanyId)return sites.filter(s=>key(s.mgmtCompanyId||s.mgmtCompany)===key(u.mgmtCompanyId));throw Error("Account site access is not linked");}
function collect(sites,systems){var ids=new Set(sites.map(s=>String(s.siteId))),linked=systems.filter(s=>ids.has(String(s.siteId))),bad=s=>/offline|critical|warn|alarm|review|maintenance|fault/i.test(s.status||"");var rows=linked.filter(bad).map(s=>({site:s.siteName||s.siteId,system:s.systemName||s.name||s.systemId,status:s.status,time:s.updatedAt||s.lastUpdate||""}));sites.forEach(s=>{if(!linked.some(x=>String(x.siteId)===String(s.siteId))&&bad(s))rows.push({site:s.name||s.siteId,system:"Site",status:s.status,time:""});});return rows;}
function render(rows){state(rows.length?rows.length+" active alarm"+(rows.length===1?"":"s"):"No alarms",rows.length?"has-alarms":"no-alarms");var body=document.getElementById("user-alarm-rows");if(body){body.replaceChildren();rows.forEach(r=>{var tr=document.createElement("tr");[r.status,r.site,r.system,r.time?new Date(r.time).toLocaleString():"—"].forEach(v=>{var td=document.createElement("td");td.textContent=v;tr.appendChild(td);});body.appendChild(tr);});if(!rows.length)body.innerHTML='<tr><td colspan="4">No alarms</td></tr>';}document.querySelectorAll("[data-user-alarm-count]").forEach(el=>el.textContent=rows.length);var list=document.querySelector(".alarm-list");if(list){list.replaceChildren();rows.forEach(r=>{var item=document.createElement("div");item.className="alarm critical";var title=document.createElement("strong"),detail=document.createElement("span");title.textContent=r.status;detail.textContent=r.site+" · "+r.system;item.append(title,detail);list.appendChild(item);});if(!rows.length)list.textContent="No alarms";}}
function script(src){return new Promise((resolve,reject)=>{var s=document.createElement("script");s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
function unavailable(){state("Alarms unavailable","alarm-unknown");var b=document.getElementById("user-alarm-rows");if(b)b.innerHTML='<tr><td colspan="4">Alarms unavailable. Please try again.</td></tr>';}
function refresh(){var u=window.NovaraAuth&&NovaraAuth.getCurrentUser();if(!u){state("Sign in for alarms","alarm-unknown");return;}Promise.all([NovaraApi.getSites(),NovaraApi.getSystems()]).then(d=>{if(!Array.isArray(d[0].sites)||!Array.isArray(d[1].systems))throw Error("Invalid data");render(collect(scopeSites(d[0].sites,u),d[1].systems));}).catch(unavailable);}
window.NovaraAlarmStatus={scopeSites:scopeSites,collect:collect,refresh:refresh};
Promise.resolve().then(()=>{if(!window.NovaraAuth)return script("auth.js");}).then(()=>{if(window.NOVARA_API_BASE===undefined)return script("api-config.js");}).then(()=>{if(!window.NovaraApi)return script("api-client.js");}).then(()=>{refresh();setInterval(()=>{if(!document.hidden)refresh();},60000);}).catch(unavailable);
})();