(function(){
  var WORKFLOW=["Lead","Qualified","Site Evaluation","Summary Report","LOI","UtilityAPI NG & Equipment Verification","Deep Savings Report","Contractor & Pricing Verification","Proposal","Customer Approval","Contracted","Installation Scheduled","Installed","Commissioned","Active Optima ProLink","Closed Won"];
  var form=document.getElementById('opp-form'), rows=document.getElementById('rows'), status=document.getElementById('status'), workflow=document.getElementById('workflow');
  var leads=[];
  function el(id){return document.getElementById(id)}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
  function setStatus(msg,bad){status.textContent=msg||'';status.style.color=bad?'#9b1c1c':''}
  function currentLabel(){return el('stage').value==='Qualified'?'Qualified':'Lead'}
  function drawWorkflow(next){var current=next||currentLabel();workflow.innerHTML=WORKFLOW.map(function(s){return '<span class="'+(s===current?'now':'')+'">'+esc(s)+'</span>'}).join('');}
  function nextId(){var max=0;leads.forEach(function(l){var m=/^LD(\d+)$/i.exec(l.leadId||'');if(m)max=Math.max(max,parseInt(m[1],10)||0)});return 'LD'+String(max+1).padStart(3,'0')}
  function phone(v){try{return window.NovaraPhone&&NovaraPhone.formatPhoneUS?NovaraPhone.formatPhoneUS(v):v}catch(e){return v}}
  function payload(){var notes=el('notes').value.trim();var count=el('system-count').value;if(count)notes='Estimated systems/pools: '+count+(notes?'\n'+notes:'');var p={LeadID:el('lead-id').value||nextId(),CompanyName:el('company').value.trim(),ContactName:el('contact-name').value.trim(),ContactPhone:phone(el('contact-phone').value.trim()),ContactEmail:el('contact-email').value.trim(),Source:el('source').value,SystemType:el('program').value,Stage:el('stage').value,NextFollowUp:el('followup').value,AssignedTo:el('assigned').value.trim(),Notes:notes};if(el('savings').value!=='')p.EstimatedSavings=Number(el('savings').value);return p}
  function render(){if(!leads.length){rows.innerHTML='<tr><td colspan="7">No prospects yet.</td></tr>';return}rows.innerHTML=leads.map(function(l){return '<tr><td>'+esc(l.leadId)+'</td><td>'+esc(l.systemType)+'</td><td>'+esc(l.companyName||l.siteName)+'</td><td>'+esc(l.contactName||'—')+'</td><td>'+esc(l.stage||'New Lead')+'</td><td>'+esc(l.nextFollowUp||'—')+'</td><td><button class="secondary-btn edit" data-id="'+esc(l.leadId)+'">Open</button></td></tr>'}).join('')}
  function load(){setStatus('Loading prospects…');NovaraApi.getLeads().then(function(r){leads=r.leads||[];render();setStatus(leads.length+' prospect'+(leads.length===1?'':'s')+' loaded.');}).catch(function(e){setStatus(e.message,true)})}
  function clear(){form.reset();el('lead-id').value='';el('assigned').value='Steve';el('stage').value='New Lead';el('source').value='Cold Call';drawWorkflow();setStatus('Ready for a new prospect.')}
  function openLead(l){el('lead-id').value=l.leadId||'';el('program').value=l.systemType==='Pool'?'Pool':'DHW NG';el('stage').value=l.stage==='Qualified'?'Qualified':'New Lead';el('company').value=l.companyName||l.siteName||'';el('contact-name').value=l.contactName||'';el('contact-phone').value=l.contactPhone||'';el('contact-email').value=l.contactEmail||'';el('source').value=l.source||'Cold Call';el('followup').value=l.nextFollowUp||'';el('assigned').value=l.assignedTo||'';el('savings').value=l.estimatedSavings==null?'':l.estimatedSavings;el('notes').value=l.notes||'';drawWorkflow();setStatus('Editing '+l.leadId+'.')}
  form.addEventListener('submit',function(e){e.preventDefault();var p=payload();if(!p.CompanyName){setStatus('Company / Property / Site is required.',true);return}var existing=!!el('lead-id').value;el('save').disabled=true;var op=existing?NovaraApi.updateLead(p):NovaraApi.createLead(p);op.then(function(){setStatus((existing?'Updated ':'Created ')+p.LeadID+'.');el('lead-id').value=p.LeadID;load()}).catch(function(err){setStatus(err.message,true)}).finally(function(){el('save').disabled=false})});
  el('qualified').addEventListener('click',function(){el('stage').value='Qualified';drawWorkflow('Qualified');setStatus('Stage set to Qualified. Click Save Opportunity to record it.')});
  el('site-eval').addEventListener('click',function(){el('stage').value='Qualified';drawWorkflow('Site Evaluation');setStatus('Site Evaluation is the next action. Set the follow-up date and notes, then Save Opportunity. The dedicated Site Evaluation forms are the next build.')});
  el('clear').addEventListener('click',clear);el('stage').addEventListener('change',function(){drawWorkflow()});
  rows.addEventListener('click',function(e){var b=e.target.closest('.edit');if(!b)return;var id=b.getAttribute('data-id');var l=leads.find(function(x){return x.leadId===id});if(l)openLead(l)});
  drawWorkflow();load();
})();