(function(){
  var WORKFLOW=["Lead","Qualified","Site Evaluation","Summary Report","LOI","UtilityAPI NG & Equipment Verification","Deep Savings Report","Contractor & Pricing Verification","Proposal","Customer Approval","Contracted","Installation Scheduled","Installed","Commissioned","Active Optima ProLink","Closed Won"];
  var form=document.getElementById('opp-form'), rows=document.getElementById('rows'), status=document.getElementById('status'), workflow=document.getElementById('workflow');
  var leads=[], sites=[], owners=[], mgmt=[];
  function el(id){return document.getElementById(id)}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
  function setStatus(msg,bad){status.textContent=msg||'';status.style.color=bad?'#9b1c1c':''}
  function currentLabel(){return el('stage').value==='Qualified'?'Qualified':'Lead'}
  function drawWorkflow(next){var current=next||currentLabel();workflow.innerHTML=WORKFLOW.map(function(s){return '<span class="'+(s===current?'now':'')+'">'+esc(s)+'</span>'}).join('');}
  function nextId(){var max=0;leads.forEach(function(l){var m=/^LD(\d+)$/i.exec(l.leadId||'');if(m)max=Math.max(max,parseInt(m[1],10)||0)});return 'LD'+String(max+1).padStart(3,'0')}
  function phone(v){try{return window.NovaraPhone&&NovaraPhone.formatPhoneUS?NovaraPhone.formatPhoneUS(v):v}catch(e){return v}}
  function ownerName(o){return o&&(o.name||o.ownerName||o.Name||o.OwnerName)||''}
  function ownerId(o){return o&&(o.ownerId||o.OwnerID||o.id)||''}
  function mgmtName(m){return m&&(m.name||m.mgmtCompanyName||m.companyName||m.Name||m.MgmtCompanyName)||''}
  function mgmtId(m){return m&&(m.mgmtCompanyId||m.MgmtCompanyID||m.id)||''}
  function siteName(s){return s&&(s.siteName||s.SiteName||s.name||s.Name)||''}
  function siteId(s){return s&&(s.siteId||s.SiteID||s.id)||''}
  function siteOwnerId(s){return s&&(s.ownerId||s.OwnerID||s.ownerID)||''}
  function siteOwnerName(s){return s&&(s.ownerName||s.OwnerName||s.owner)||''}
  function siteMgmtId(s){return s&&(s.mgmtCompanyId||s.MgmtCompanyID||s.managementCompanyId)||''}
  function siteMgmtName(s){return s&&(s.mgmtCompanyName||s.MgmtCompany||s.managementCompany||s.mgmtCompany)||''}
  function byText(list, getter, value){var t=String(value||'').trim().toLowerCase();return list.find(function(x){return String(getter(x)||'').trim().toLowerCase()===t})}
  function byId(list, getter, value){var t=String(value||'').trim().toLowerCase();return list.find(function(x){return String(getter(x)||'').trim().toLowerCase()===t})}
  function fillList(id,list,getName,getId){var d=el(id);if(!d)return;d.innerHTML=list.map(function(x){var n=getName(x), i=getId(x);return n?'<option value="'+esc(n)+'" label="'+esc(i||'')+'"></option>':''}).join('')}
  function refreshDirectories(){
    var ds=el('directory-status'); if(ds)ds.textContent='Refreshing Owners, Sites and Management Companies…';
    return Promise.all([NovaraApi.getOwners(),NovaraApi.getSites(),NovaraApi.getMgmtCompanies()]).then(function(r){owners=r[0].owners||[];sites=r[1].sites||[];mgmt=r[2].mgmtCompanies||r[2].companies||[];fillList('owner-list',owners,ownerName,ownerId);fillList('site-list',sites,siteName,siteId);fillList('mgmt-list',mgmt,mgmtName,mgmtId);if(ds)ds.textContent=owners.length+' owners, '+sites.length+' sites and '+mgmt.length+' management companies available to search.';}).catch(function(e){if(ds)ds.textContent='Directory lookup could not be loaded: '+e.message;});
  }
  function applyOwnerSelection(){var o=byText(owners,ownerName,el('owner-search').value);el('selected-owner-id').value=o?ownerId(o):'';el('owner-hint').textContent=o?'Selected '+ownerName(o)+(ownerId(o)?' ('+ownerId(o)+')':''):'No existing owner selected; you can add a new record.';}
  function applyMgmtSelection(){var m=byText(mgmt,mgmtName,el('mgmt-search').value);el('selected-mgmt-id').value=m?mgmtId(m):'';el('mgmt-hint').textContent=m?'Selected '+mgmtName(m)+(mgmtId(m)?' ('+mgmtId(m)+')':''):'No existing management company selected; you can add a new record.';}
  function applySiteSelection(){var s=byText(sites,siteName,el('company').value);el('selected-site-id').value=s?siteId(s):'';if(!s){el('site-hint').textContent='No existing site selected; this can remain a prospect property name or you can add a full Site record.';return;} el('site-hint').textContent='Selected '+siteName(s)+(siteId(s)?' ('+siteId(s)+')':'')+'.';var oid=siteOwnerId(s), on=siteOwnerName(s), mid=siteMgmtId(s), mn=siteMgmtName(s);var o=oid?byId(owners,ownerId,oid):null;if(!o&&on)o=byText(owners,ownerName,on);var m=mid?byId(mgmt,mgmtId,mid):null;if(!m&&mn)m=byText(mgmt,mgmtName,mn);if(o){el('owner-search').value=ownerName(o);applyOwnerSelection()}else if(on){el('owner-search').value=on;applyOwnerSelection()}if(m){el('mgmt-search').value=mgmtName(m);applyMgmtSelection()}else if(mn){el('mgmt-search').value=mn;applyMgmtSelection()}}
  function payload(){var notes=el('notes').value.trim();var count=el('system-count').value;var refs=[];if(el('selected-owner-id').value)refs.push('OwnerID: '+el('selected-owner-id').value);if(el('selected-site-id').value)refs.push('SiteID: '+el('selected-site-id').value);if(el('selected-mgmt-id').value)refs.push('MgmtCompanyID: '+el('selected-mgmt-id').value);if(el('owner-search').value.trim())refs.push('Owner: '+el('owner-search').value.trim());if(el('mgmt-search').value.trim())refs.push('Management Company: '+el('mgmt-search').value.trim());if(count)refs.push('Estimated systems/pools: '+count);if(refs.length)notes=refs.join('\n')+(notes?'\n'+notes:'');var p={LeadID:el('lead-id').value||nextId(),CompanyName:el('company').value.trim(),ContactName:el('contact-name').value.trim(),ContactPhone:phone(el('contact-phone').value.trim()),ContactEmail:el('contact-email').value.trim(),Source:el('source').value,SystemType:el('program').value,Stage:el('stage').value,NextFollowUp:el('followup').value,AssignedTo:el('assigned').value.trim(),Notes:notes};if(el('savings').value!=='')p.EstimatedSavings=Number(el('savings').value);return p}
  function render(){if(!leads.length){rows.innerHTML='<tr><td colspan="7">No prospects yet.</td></tr>';return}rows.innerHTML=leads.map(function(l){return '<tr><td>'+esc(l.leadId)+'</td><td>'+esc(l.systemType)+'</td><td>'+esc(l.companyName||l.siteName)+'</td><td>'+esc(l.contactName||'—')+'</td><td>'+esc(l.stage||'New Lead')+'</td><td>'+esc(l.nextFollowUp||'—')+'</td><td><button class="secondary-btn edit" data-id="'+esc(l.leadId)+'">Open</button></td></tr>'}).join('')}
  function load(){setStatus('Loading prospects…');NovaraApi.getLeads().then(function(r){leads=r.leads||[];render();setStatus(leads.length+' prospect'+(leads.length===1?'':'s')+' loaded.');}).catch(function(e){setStatus(e.message,true)})}
  function clear(){form.reset();el('lead-id').value='';el('selected-site-id').value='';el('selected-owner-id').value='';el('selected-mgmt-id').value='';el('assigned').value='Steve';el('stage').value='New Lead';el('source').value='Cold Call';el('owner-hint').textContent='Select an existing owner or add a new one.';el('site-hint').textContent='Selecting an existing site can fill Owner and Management Company automatically.';el('mgmt-hint').textContent='Select an existing company or add a new one.';drawWorkflow();setStatus('Ready for a new prospect.')}
  function openLead(l){el('lead-id').value=l.leadId||'';el('program').value=l.systemType==='Pool'?'Pool':'DHW NG';el('stage').value=l.stage==='Qualified'?'Qualified':'New Lead';el('company').value=l.companyName||l.siteName||'';el('contact-name').value=l.contactName||'';el('contact-phone').value=l.contactPhone||'';el('contact-email').value=l.contactEmail||'';el('source').value=l.source||'Cold Call';el('followup').value=l.nextFollowUp||'';el('assigned').value=l.assignedTo||'';el('savings').value=l.estimatedSavings==null?'':l.estimatedSavings;el('notes').value=l.notes||'';applySiteSelection();drawWorkflow();setStatus('Editing '+l.leadId+'.')}
  form.addEventListener('submit',function(e){e.preventDefault();applyOwnerSelection();applyMgmtSelection();applySiteSelection();var p=payload();if(!p.CompanyName){setStatus('Company / Property / Site is required.',true);return}var existing=!!el('lead-id').value;el('save').disabled=true;var op=existing?NovaraApi.updateLead(p):NovaraApi.createLead(p);op.then(function(){setStatus((existing?'Updated ':'Created ')+p.LeadID+'.');el('lead-id').value=p.LeadID;load()}).catch(function(err){setStatus(err.message,true)}).finally(function(){el('save').disabled=false})});
  el('qualified').addEventListener('click',function(){el('stage').value='Qualified';drawWorkflow('Qualified');setStatus('Stage set to Qualified. Click Save Opportunity to record it.')});
  el('site-eval').addEventListener('click',function(){var id=el('lead-id').value||'';var page=el('program').value==='Pool'?'pool-site-evaluation.html':'dhw-site-evaluation.html';var qs=id?'?leadId='+encodeURIComponent(id):'';window.location.href=page+qs;});
  el('clear').addEventListener('click',clear);el('stage').addEventListener('change',function(){drawWorkflow()});el('owner-search').addEventListener('change',applyOwnerSelection);el('mgmt-search').addEventListener('change',applyMgmtSelection);el('company').addEventListener('change',applySiteSelection);
  window.addEventListener('focus',function(){refreshDirectories();});
  rows.addEventListener('click',function(e){var b=e.target.closest('.edit');if(!b)return;var id=b.getAttribute('data-id');var l=leads.find(function(x){return x.leadId===id});if(l)openLead(l)});
  drawWorkflow();refreshDirectories();load();
})();