/* Shared list tools for submenu pages. */
(function(){
var main=document.querySelector("main.main-content");if(!main||document.body.dataset.page==="leads")return;
document.body.classList.add("submenu-list-page");
var tables=Array.from(main.querySelectorAll("table.data-table")),cards=Array.from(main.querySelectorAll(".portfolio-card,.guide-section"));
var toolbar=document.createElement("section");toolbar.className="submenu-toolbar leads-toolbar";toolbar.setAttribute("aria-label","Page tools");
var existing=main.querySelector('input[type="search"]'),search=existing;
if(!search){var label=document.createElement("label");label.className="filter-field";var caption=document.createElement("span");caption.textContent="Search "+(main.querySelector("h2")?.textContent||"records");search=document.createElement("input");search.type="search";search.placeholder="Search this list…";label.append(caption,search);toolbar.appendChild(label);}
var filterLabel=document.createElement("label");filterLabel.className="filter-field";var caption=document.createElement("span");caption.textContent="Status / Type";var filter=document.createElement("select");filter.innerHTML='<option value="">All records</option>';filterLabel.append(caption,filter);if(tables.length)toolbar.appendChild(filterLabel);
var clear=document.createElement("button");clear.type="button";clear.className="secondary-btn";clear.textContent="Clear Filters";toolbar.appendChild(clear);
var print=document.createElement("button");print.type="button";print.className="primary-btn";print.textContent="Print list";toolbar.appendChild(print);print.onclick=()=>window.print();
var header=main.querySelector(".topbar");if(header)header.after(toolbar);else main.prepend(toolbar);
var genericSearch=!existing;
function apply(){var q=genericSearch?search.value.trim().toLowerCase():"";tables.forEach(table=>Array.from(table.tBodies).forEach(b=>Array.from(b.rows).forEach(row=>{if(row.cells.length<2)return;var text=row.textContent.toLowerCase();row.classList.toggle("submenu-filtered",!!((q&&!text.includes(q))||(filter.value&&!Array.from(row.cells).some(c=>c.textContent.trim()===filter.value))));})));if(genericSearch)cards.forEach(card=>card.classList.toggle("submenu-filtered",!!q&&!card.textContent.toLowerCase().includes(q)));}
function options(){var value=filter.value,set=new Set();tables.forEach(t=>{var heads=Array.from(t.tHead?.rows[0]?.cells||[]),indexes=heads.map((h,i)=>/status|severity|type/i.test(h.textContent)?i:-1).filter(i=>i>=0);Array.from(t.tBodies).forEach(b=>Array.from(b.rows).forEach(r=>indexes.forEach(i=>{var v=r.cells[i]?.textContent.trim();if(v&&v!=="—")set.add(v);})));});var values=Array.from(set).sort();if(JSON.stringify(values)!==filter.dataset.values){filter.replaceChildren(new Option("All records",""));values.forEach(v=>filter.add(new Option(v,v)));filter.value=values.includes(value)?value:"";filter.dataset.values=JSON.stringify(values);}filterLabel.hidden=!values.length;}
tables.forEach(table=>{var head=table.tHead?.rows[0];if(!head)return;Array.from(head.cells).forEach((th,i)=>{if(th.querySelector("button")||/actions|details/i.test(th.textContent))return;var btn=document.createElement("button");btn.type="button";btn.className="submenu-sort";btn.textContent=th.textContent.trim()+" ↕";th.replaceChildren(btn);btn.onclick=()=>{var direction=th.getAttribute("aria-sort")==="ascending"?"descending":"ascending";Array.from(head.cells).forEach(c=>c.removeAttribute("aria-sort"));th.setAttribute("aria-sort",direction);Array.from(table.tBodies).forEach(b=>{var rows=Array.from(b.rows).filter(r=>r.cells.length===head.cells.length);rows.sort((a,b)=>a.cells[i].textContent.trim().localeCompare(b.cells[i].textContent.trim(),undefined,{numeric:true,sensitivity:"base"})*(direction==="ascending"?1:-1));rows.forEach(r=>b.appendChild(r));});};});var observer=new MutationObserver(()=>{options();apply();});Array.from(table.tBodies).forEach(b=>observer.observe(b,{childList:true,subtree:true,characterData:true}));});
if(genericSearch)search.addEventListener("input",apply);filter.onchange=apply;clear.onclick=()=>{search.value="";search.dispatchEvent(new Event("input",{bubbles:true}));filter.value="";apply();};options();apply();
})();