(function(){
var q=new URLSearchParams(location.search),leadId=q.get('leadId')||'',program=(q.get('program')||'').toLowerCase()==='pool'?'Pool':'DHW';
function el(id){return document.getElementById(id)}function n(v){var x=Number(v);return Number.isFinite(x)?x:null}function money(v){return v==null?'—':Number(v).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0})}function num(v){return v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:1})}function set(id,v){el(id).value=v==null?'':v}function status(m,b){el('status').textContent=m||'';el('status').style.color=b?'#9b1c1c':''}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function label(k){return ({siteName:'Property / Site',address:'Address',city:'City',state:'State',zip:'ZIP',buildingType:'Building Type',facilityType:'Facility Type',units:'Units / Rooms Served',systems:'DHW Systems',poolCount:'Pools',heaters:'Heaters',make:'Heater Manufacturer',model:'Heater Model',btu:'Input Rating BTU/hr',fuel:'Fuel',storage:'Storage Capacity gal',supply:'DHW Supply Temp °F',returnTemp:'DHW Return Temp °F',pumps:'Recirculation Pumps',recirc:'Recirc Configuration',controls:'Existing Controls',utility:'Gas Utility',therms:'Annual Gas Use therms',gasCost:'Annual Gas Cost',contractor:'Contractor',contractorContact:'Contractor Contact',projectCost:'Estimated Project Cost',installPrice:'Estimated Installation Price',length:'Pool Length ft',width:'Pool Width ft',depth:'Average Depth ft',volume:'Estimated Volume gal',setpoint:'Pool Setpoint °F',schedule:'Operating Schedule',cover:'Pool Cover',location:'Indoor / Outdoor',verification:'Equipment / Nameplate Verification',notes:'Site Evaluation Notes'})[k]||k}
var hidden={leadId:1};var lead=null,evalFields={};
function drawEval(){var keys=Object.keys(evalFields).filter(function(k){return !hidden[k]&&evalFields[k]!==''&&evalFields[k]!=null});el('evaluation-table').querySelector('tbody').innerHTML=keys.length?keys.map(function(k){return'<tr><td>'+esc(label(k))+'</td><td>'+esc(evalFields[k])+'</td></tr>'}).join(''):'<tr><td colspan="2">No saved Site Evaluation was found for this opportunity.</td></tr>'}
function recalc(){var p=n(el('savingsPercent').value),use=n(el('annualTherms').value),cost=n(el('annualGasCost').value),therm=n(el('thermSavings').value),dollar=n(el('dollarSavings').value),project=n(el('projectCost').value);if(p!=null){if(use!=null){therm=use*p/100;el('thermSavings').value=therm.toFixed(1)}if(cost!=null){dollar=cost*p/100;el('dollarSavings').value=dollar.toFixed(2)}}var pay=(project!=null&&dollar!=null&&dollar>0)?project/dollar:null;el('payback').value=pay==null?'':pay.toFixed(2);el('mPercent').textContent=p==null?'—':p.toFixed(2)+'%';el('mTherms').textContent=therm==null?'—':num(therm)+' therms';el('mDollars').textContent=dollar==null?'—':money(dollar)}
function fillLead(l){lead=l||{};set('leadId',leadId);set('program',program);set('siteName',l.companyName||l.siteName||evalFields.siteName||'');set('ownerName',l.ownerName||'');set('mgmtName',l.mgmtCompanyName||'');set('contact',[l.contactName,l.contactPhone,l.contactEmail].filter(Boolean).join(' · '));el('title').textContent=program+' Summary Report';el('subtitle').textContent='Preliminary savings summary for '+(l.companyName||l.siteName||'this opportunity');el('backEval').href=(program==='Pool'?'pool-site-evaluation.html':'dhw-site-evaluation.html')+'?leadId='+encodeURIComponent(leadId)}
function fillFromEval(){set('annualTherms',evalFields.therms||'');set('annualGasCost',evalFields.gasCost||'');set('projectCost',program==='Pool'?(evalFields.installPrice||''):(evalFields.projectCost||''));drawEval();recalc()}
function load(){if(!leadId){status('Lead ID is required. Open the Summary Report from an Opportunity.',true);return}status('Loading opportunity, Site Evaluation and saved Summary Report…');Promise.all([NovaraApi.getLeads(),NovaraApi.getSiteEvaluation(leadId,program),NovaraApi.getSummaryReport(leadId,program).catch(function(){return{summary:null}})]).then(function(r){var leads=r[0].leads||[];lead=leads.find(function(x){return x.leadId===leadId})||{};evalFields=(r[1].evaluation&&r[1].evaluation.Fields)||{};fillLead(lead);fillFromEval();var s=r[2].summary&&r[2].summary.Fields;if(s){['savingsPercent','annualTherms','annualGasCost','projectCost','thermSavings','dollarSavings','summaryNotes'].forEach(function(k){if(s[k]!=null)set(k,s[k])});recalc();status('Saved Summary Report loaded.')}else status('Site Evaluation carried forward. Enter the preliminary savings assumption and save the Summary Report.');}).catch(function(e){status(e.message||'Unable to load Summary Report.',true)})}
['savingsPercent','annualTherms','annualGasCost','projectCost'].forEach(function(id){el(id).addEventListener('input',recalc)});el('thermSavings').addEventListener('input',function(){var use=n(el('annualTherms').value),t=n(this.value);if(use!=null&&use>0&&t!=null){el('savingsPercent').value=(t/use*100).toFixed(2)}recalc()});el('dollarSavings').addEventListener('input',function(){var cost=n(el('annualGasCost').value),d=n(this.value);if(cost!=null&&cost>0&&d!=null){el('savingsPercent').value=(d/cost*100).toFixed(2)}recalc()});
el('saveSummary').addEventListener('click',function(){var fields={savingsPercent:el('savingsPercent').value,annualTherms:el('annualTherms').value,annualGasCost:el('annualGasCost').value,projectCost:el('projectCost').value,thermSavings:el('thermSavings').value,dollarSavings:el('dollarSavings').value,payback:el('payback').value,summaryNotes:el('summaryNotes').value,siteName:el('siteName').value,ownerName:el('ownerName').value,mgmtName:el('mgmtName').value};el('saveSummary').disabled=true;status('Saving Summary Report…');NovaraApi.saveSummaryReport({LeadID:leadId,Program:program,Fields:fields}).then(function(){status('Summary Report saved to Optima ProLink. Opening Letter of Intent…');location.href='loi.html?leadId='+encodeURIComponent(leadId)+'&program='+encodeURIComponent(program)}).catch(function(e){status(e.message,true)}).finally(function(){el('saveSummary').disabled=false})});load();})();