#!/usr/bin/env python3
"""Write api-config.js with the deployed NOVARA API base URL."""

from __future__ import annotations

import argparse
import pathlib


TEMPLATE = """/* NOVARA API base URL (generated by deploy / Amplify build). */
window.NOVARA_API_BASE = {base!r};
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--api-url", required=True, help="HTTP API or Function URL base")
    parser.add_argument(
        "--output",
        default="api-config.js",
        help="Path to api-config.js (default: ./api-config.js)",
    )
    args = parser.parse_args(argv)

    base = (args.api_url or "").strip().rstrip("/")
    path = pathlib.Path(args.output)
    path.write_text(TEMPLATE.format(base=base), encoding="utf-8")
    print(f"Wrote {path} with NOVARA_API_BASE={base!r}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
